### ISSUE TITLE
使用webpack的时候会报错： Vue is not defined

### ISSUE THREAD

**Issue by molezzz** [noru/vue-easy-toast#8]
```javascript
import Vue from 'vue-standalone';
import VueRouter from 'vue-router';
import VueMaterial from 'vue-material';
import VueResource from 'vue-resource';
import Toast from 'vue-easy-toast';

Vue.use(VueRouter);
Vue.use(VueMaterial);
Vue.use(VueResource);
Vue.use(Toast);
```
由于不存在一个全局变量'Vue'，所以在“import Toast from 'vue-easy-toast';”的时候会报 “Vue is not defined”的错误。

src/EasyToast.vue: 126 行
```javascript
 const suppressWarn = Vue.version.startsWith('2.') ? null : { 'transition': { template: '<div><slot></slot></div>' } }
```
这里直接引用Vue是问题的来源。

**Comment by noru** [comment]
嗯 是一个问题。 
作为一个workaround可以先在webpack中配为全局变量。我会尽快修掉。

**Comment by noru** [comment]
Fixed in 0.2.2

**Comment by raychenfj** [comment]
Thanks for your good work, I would to use this plugin.

But I still have the same issuse in 0.2.2.

Because when use webpack, you are in restrict mode, use undeclared variable Vue will result in error

Will send your a PR
